logging:
  level:
    ROOT: INFO
    com.albedo.java: ${logback.loglevel}
    com.albedo.java.plugins.database.interceptor: INFO
server:
  port: 8061
  servlet:
    session:
      timeout: 30m

spring:
  redis:
    host: localhost
    lettuce:
      pool:
        max-idle: 10
        min-idle: 10
        max-active: 100
  web:
    root:
      prefix: albedo-ui/dist/




# ===================================================================
# Albedo specific properties
# ===================================================================

application:
  developMode: true
  rabbitmq:
    enabled: false
    ip: 127.0.0.1
    port: 5672
    username: albedo
    password: albedo
  mysql:
    ip: 127.0.0.1
    port: 3306
    driverClassName: com.mysql.cj.jdbc.Driver
    database: albedo
    username: root
    password: 111111
    url: jdbc:mysql://${application.mysql.ip}:${application.mysql.port}/${application.mysql.database}?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
  security:
    authentication:
      jwt:
        # 必须使用最少88位的Base64对该令牌进行编码
        base64-secret: bXktc2VjcmV0LWtleS13aGljaC1zaG91bGQtYmUtY2hhbmdlZC1pbi1wcm9kdWN0aW9uLWFuZC1iZS1iYXNlNjQtZW5jb2RlZAo=
        # Token is valid 24 hours
        token-validity-in-seconds: 300
        token-validity-in-seconds-for-remember-me: 2592000
