version: '3'
services:
  albedo-mysql:
    build:
      context: ./
      dockerfile: ./db/Dockerfile
    restart: always
    container_name: albedo-mysql
    image: albedo-mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 111111
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      TZ: Asia/Shanghai
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
#    volumes:
#      - ./mysql/data:/var/lib/mysql
#      - ./mysql/log:/var/log/mysql
#      - ./mysql/config:/etc/mysql

  albedo-redis:
    image: redis:6.0
    ports:
      - 6379:6379
    restart: always
    container_name: albedo-redis
    hostname: albedo-redis

  albedo-admin:
    build:
      context: ./albedo-modules/albedo-admin
    restart: always
    container_name: albedo-admin
    hostname: albedo-admin
    image: albedo-admin

  albedo-api:
    build:
      context: ./albedo-modules/albedo-app
    restart: always
    ports:
      - 4001:4001
    container_name: albedo-app
    hostname: albedo-app
    image: albedo-api

  albedo-quartz:
    build:
      context: ./albedo-modules/albedo-quartz
    restart: always
    ports:
      - 4002:4002
    container_name: albedo-quartz
    hostname: albedo-quartz
    image: albedo-quartz

  albedo-ui:
    build:
      context: ./albedo-ui
    restart: always
    container_name: albedo-ui
    hostname: albedo-ui
    image: albedo-ui
    ports:
      - 8081:80
