version: '2'
services:
  albedo-mysql:
    build:
      context: ./
      dockerfile: ./db/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    container_name: albedo-mysql
    image: albedo-mysql
    ports:
      - 3306:3306

  albedo-redis:
    image: redis:5.0
    ports:
      - 6379:6379
    restart: always
    container_name: albedo-redis
    hostname: albedo-redis

  albedo-admin:
    build:
      context: ./
      dockerfile: ./albedo-admin/albedo-admin-biz/Dockerfile
    restart: always
    container_name: albedo-admin
    hostname: albedo-admin
    image: albedo-admin

