logging:
  level:
    ROOT: INFO
    com.albedo.java: ${logback.loglevel}
server:
  port: 4001

spring:
  redis:
    host: albedo-redis

# ===================================================================
# Albedo specific properties
# ===================================================================

application:
  swagger:
    enabled: false
  rabbitmq:
    enabled: false
    ip: 127.0.0.1
    port: 5672
    username: albedo
    password: albedo
  mysql:
    ip: albedo-mysql
    port: 3306
    driverClassName: com.mysql.cj.jdbc.Driver
    database: albedo
    username: root
    password: 111111
    url: jdbc:mysql://${application.mysql.ip}:${application.mysql.port}/${application.mysql.database}?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
  security:
    authentication:
      jwt:
        base64-secret: bXktc2VjcmV0LWtleS13aGljaC1zaG91bGQtYmUtY2hhbmdlZC1pbi1wcm9kdWN0aW9uLWFuZC1iZS1iYXNlNjQtZW5jb2RlZAo=
        # Token is valid 24 hours
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
